a=int(input("enter the no to get name of month  "))
if (a==1):print("january")
elif (a==2): print("feburary")
elif (a==3): print("march")
elif (a==4): print("april")
elif (a==5): print("may")
elif (a==6): print("june")
elif (a==7): print("july")
elif (a==8): print("agust")
elif (a==9): print("september")
elif (a==10): print("october")
elif (a==11): print("november")
elif (a==12): print("december")

